version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "my-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-zsn5sfnhnem3"
s3_prefix = "my-app"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
